[project]
name = "synthetic-datagen"
version = "0.1.0"
description = "Using Faker to generate synthetic pension scheme member data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=36.1.1",
    "polars>=1.23.0",
]
